import type { PurchaseRequest, PurchaseRequestItem } from './purchase-request';
import type { User } from './user';

// ─── Status enum ────────────────────────────────────────────────────────────

export const PurchaseOrderStatus = {
  Draft: 'draft',
  ForSignature: 'for_signature',
  Signed: 'signed',
  Acknowledged: 'acknowledged',
  Completed: 'completed',
} as const;

export type PurchaseOrderStatus =
  (typeof PurchaseOrderStatus)[keyof typeof PurchaseOrderStatus];

// ─── Core entities ──────────────────────────────────────────────────────────

export interface PurchaseOrder {
  id: number;
  /** Auto-generated by the system when PPU creates the PO record */
  po_number: string;
  purchase_request_id: number;
  prepared_by_id: number;
  supplier_name: string | null;
  supplier_address: string | null;
  delivery_terms: string | null;
  payment_terms: string | null;
  /** ISO date string: YYYY-MM-DD */
  delivery_date: string | null;
  /** Decimal stored as string */
  total_amount: string;
  status: PurchaseOrderStatus;
  /** Relative storage path to the uploaded signed PO document */
  signed_po_path: string | null;
  created_at: string;
  updated_at: string;
  // Relations (present when eager-loaded by the API)
  purchase_request?: PurchaseRequest;
  prepared_by?: User;
  items?: PurchaseOrderItem[];
}

export interface PurchaseOrderItem {
  id: number;
  purchase_order_id: number;
  /** Nullable; links back to the originating PR line item for traceability */
  pr_item_id: number | null;
  item_description: string;
  unit_of_measure: string;
  /** Decimal stored as string */
  quantity: string;
  /** Decimal stored as string */
  unit_cost: string;
  /** Decimal stored as string */
  total_cost: string;
  created_at: string;
  updated_at: string;
  // Relations
  pr_item?: PurchaseRequestItem;
}

// ─── Payload types ──────────────────────────────────────────────────────────

export interface CreatePurchaseOrderItemPayload {
  pr_item_id?: number;
  item_description: string;
  unit_of_measure: string;
  quantity: number;
  unit_cost: number;
}

export interface CreatePurchaseOrderPayload {
  purchase_request_id: number;
  supplier_name?: string;
  supplier_address?: string;
  delivery_terms?: string;
  payment_terms?: string;
  /** ISO date string: YYYY-MM-DD */
  delivery_date?: string;
  items: CreatePurchaseOrderItemPayload[];
}

export interface UpdatePurchaseOrderPayload {
  supplier_name?: string;
  supplier_address?: string;
  delivery_terms?: string;
  payment_terms?: string;
  delivery_date?: string | null;
  status?: PurchaseOrderStatus;
  items?: CreatePurchaseOrderItemPayload[];
}
