import type { User } from './user';

// ─── Status enum ────────────────────────────────────────────────────────────

export const RfqStatus = {
  Draft: 'draft',
  ForSignature: 'for_signature',
  Signed: 'signed',
  Canvassing: 'canvassing',
  Closed: 'closed',
} as const;

export type RfqStatus = (typeof RfqStatus)[keyof typeof RfqStatus];

// ─── Core entities ──────────────────────────────────────────────────────────

export interface Rfq {
  id: number;
  /** Auto-generated by the system when PPU creates the RFQ record */
  rfq_number: string;
  purchase_request_id: number;
  prepared_by_id: number;
  /** ISO date string: YYYY-MM-DD; submission deadline for canvassers */
  deadline: string | null;
  status: RfqStatus;
  // file_path is write-only — never returned by the API; the signed RFQ
  // document itself is retrieved via the pr_attachments download route.
  created_at: string;
  updated_at: string;
  // Relations (present when eager-loaded by the API)
  prepared_by?: User;
  items?: RfqItem[];
}

export interface RfqItem {
  id: number;
  rfq_id: number;
  /** Links back to the originating PR line item for traceability */
  pr_item_id: number;
  item_description: string;
  unit_of_measure: string;
  /** Decimal stored as string */
  quantity: string;
  created_at: string;
  updated_at: string;
  // Relations
  canvass_responses?: CanvassResponse[];
}

export interface CanvassResponse {
  id: number;
  rfq_id: number;
  rfq_item_id: number;
  supplier_name: string;
  /** Decimal stored as string */
  unit_price: string;
  /** Decimal stored as string */
  total_price: string;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// ─── Payload types ──────────────────────────────────────────────────────────

export interface CreateRfqPayload {
  purchase_request_id: number;
  prepared_by_id: number;
  /** ISO date string: YYYY-MM-DD */
  deadline?: string;
  status?: RfqStatus;
  /** Storage path of an already-uploaded pr_attachment (type: 'rfq') */
  file_path?: string;
}

export interface UpdateRfqPayload {
  prepared_by_id?: number;
  deadline?: string | null;
  status?: RfqStatus;
  file_path?: string;
}

export interface CreateRfqItemPayload {
  rfq_id: number;
  pr_item_id: number;
  item_description: string;
  unit_of_measure: string;
  quantity: number;
}

export interface UpdateRfqItemPayload {
  rfq_id?: number;
  pr_item_id?: number;
  item_description?: string;
  unit_of_measure?: string;
  quantity?: number;
}

export interface CreateCanvassResponsePayload {
  rfq_id: number;
  rfq_item_id: number;
  supplier_name: string;
  unit_price: number;
  /** Required by the API — not computed server-side */
  total_price: number;
  notes?: string;
}

export interface UpdateCanvassResponsePayload {
  rfq_id?: number;
  rfq_item_id?: number;
  supplier_name?: string;
  unit_price?: number;
  total_price?: number;
  notes?: string | null;
}
