import type { PurchaseRequest, PurchaseRequestItem } from './purchase-request';
import type { User } from './user';

// ─── Status enum ────────────────────────────────────────────────────────────

export const RfqStatus = {
  Draft: 'draft',
  ForSignature: 'for_signature',
  Signed: 'signed',
  Canvassing: 'canvassing',
  Closed: 'closed',
} as const;

export type RfqStatus = (typeof RfqStatus)[keyof typeof RfqStatus];

// ─── Core entities ──────────────────────────────────────────────────────────

export interface Rfq {
  id: number;
  /** Auto-generated by the system when PPU creates the RFQ record */
  rfq_number: string;
  purchase_request_id: number;
  prepared_by_id: number;
  /** ISO date string: YYYY-MM-DD; submission deadline for canvassers */
  deadline: string | null;
  status: RfqStatus;
  /** Relative storage path to the uploaded signed RFQ document */
  file_path: string | null;
  created_at: string;
  updated_at: string;
  // Relations (present when eager-loaded by the API)
  purchase_request?: PurchaseRequest;
  prepared_by?: User;
  items?: RfqItem[];
  canvass_responses?: CanvassResponse[];
}

export interface RfqItem {
  id: number;
  rfq_id: number;
  /** Links back to the originating PR line item for traceability */
  pr_item_id: number;
  item_description: string;
  unit_of_measure: string;
  /** Decimal stored as string */
  quantity: string;
  created_at: string;
  updated_at: string;
  // Relations
  pr_item?: PurchaseRequestItem;
  canvass_responses?: CanvassResponse[];
}

export interface CanvassResponse {
  id: number;
  rfq_id: number;
  rfq_item_id: number;
  supplier_name: string;
  /** Decimal stored as string */
  unit_price: string;
  /** Decimal stored as string */
  total_price: string;
  notes: string | null;
  created_at: string;
  updated_at: string;
  // Relations
  rfq_item?: RfqItem;
}

// ─── Payload types ──────────────────────────────────────────────────────────

export interface CreateRfqItemPayload {
  pr_item_id: number;
  item_description: string;
  unit_of_measure: string;
  quantity: number;
}

export interface CreateRfqPayload {
  purchase_request_id: number;
  /** ISO date string: YYYY-MM-DD */
  deadline?: string;
  items: CreateRfqItemPayload[];
}

export interface CreateCanvassResponsePayload {
  rfq_item_id: number;
  supplier_name: string;
  unit_price: number;
}
